name: berhentikok
description: Aplikasi Berhenti Merokok.

version: 1.0.1+5

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  copy_with_extension: ^4.0.3
  copy_with_extension_gen: ^4.0.3
  dio: ^4.0.6
  firebase_storage: ^11.0.5
  fl_chart: ^0.55.0
  flutter_bloc: ^8.0.0
  flutter_html: ^2.2.1
  flutter_launcher_icons: "^0.9.2"
  flutter_screenutil: ^5.5.3+2
  fluttertoast: ^8.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.3
  intl: ^0.17.0
  round_spot: ^0.5.0
  table_calendar: ^3.0.6
  firebase_core: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  change_app_package_name: ^1.1.0
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/health/
    - assets/icons/
    - assets/achievement/
    - assets/contents/
  
  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
