name: berhentikok
description: Aplikasi Berhenti Merokok.

version: 1.1.3+16

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.2
  copy_with_extension: ^5.0.4
  copy_with_extension_gen: ^5.0.4
  draggable_fab: ^0.1.4
  fl_chart: ^1.0.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.5.3+2
  fluttertoast: ^8.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  intl: ^0.20.2
  percent_indicator: ^4.2.2
  table_calendar: ^3.0.6
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  change_app_package_name: ^1.1.0
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/health/
    - assets/icons/
    - assets/achievement/
    - assets/contents/
    - assets/tips/
  
  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
